package schema

import (
	"fmt"
	"sort"
	"strings"
)

// Statement는 실행 단위 SQL 한 문장이다.
type Statement struct {
	SQL         string     `json:"sql"`
	Kind        ChangeKind `json:"kind"`
	Table       string     `json:"table,omitempty"`
	Object      string     `json:"object,omitempty"`
	Destructive bool       `json:"destructive"`
	// Note는 이 문장에 대한 주의사항이다 (예: SQLite 제약, 수동 확인 필요).
	Note string `json:"note,omitempty"`
}

// Plan은 마이그레이션 실행 계획이다. Up과 Down이 짝을 이룬다.
type Plan struct {
	Dialect string      `json:"dialect"`
	Up      []Statement `json:"up"`
	Down    []Statement `json:"down"`
	// Warnings는 계획 생성 중 발견된 문제다. 비어 있지 않으면 UI가 눈에 띄게 표시한다.
	Warnings []string `json:"warnings,omitempty"`
	// Irreversible은 down SQL을 만들 수 없는 변경이 있었음을 뜻한다.
	Irreversible []string `json:"irreversible,omitempty"`
}

func (p *Plan) UpSQL() string   { return joinStatements(p.Up) }
func (p *Plan) DownSQL() string { return joinStatements(p.Down) }

func joinStatements(stmts []Statement) string {
	var b strings.Builder
	for _, s := range stmts {
		if s.Note != "" {
			fmt.Fprintf(&b, "-- %s\n", s.Note)
		}
		b.WriteString(s.SQL)
		if !strings.HasSuffix(strings.TrimSpace(s.SQL), ";") {
			b.WriteString(";")
		}
		b.WriteString("\n")
	}
	return b.String()
}

// dialectQuirks는 DDL 생성에서 dialect별로 갈리는 부분을 모아둔다.
type dialectQuirks struct {
	quoteOpen  string
	quoteClose string
	// supportsAlterColumnType이 false면 컬럼 타입 변경에 테이블 재작성이 필요하다.
	supportsAlterColumnType bool
	// supportsDropColumn이 false면 컬럼 삭제를 지원하지 않는다.
	supportsDropColumn bool
	// supportsInlineComment이 true면 COMMENT를 컬럼 정의에 붙일 수 있다 (MySQL).
	supportsInlineComment bool
	// commentStatement가 true면 COMMENT ON 문을 별도로 낸다 (PostgreSQL, Oracle).
	commentStatement bool
	// ifExists는 DROP에 IF EXISTS를 붙일 수 있는지 여부다.
	ifExists bool
	// ifNotExists는 CREATE에 IF NOT EXISTS를 붙일 수 있는지 여부다.
	ifNotExists bool
	// identityClause는 자동증가 컬럼 표현이다.
	identityClause string
	// alterColumnTypeTemplate은 타입 변경 문법이다. %s는 순서대로 테이블, 컬럼, 타입.
	alterColumnType func(q *dialectQuirks, table, col, typ string, nullable bool) string
	// setNotNull / dropNotNull은 NULL 허용 변경 문법이다.
	setNullability func(q *dialectQuirks, table, col, typ string, nullable bool) string
	setDefault     func(q *dialectQuirks, table, col, def string) string
	dropDefault    func(q *dialectQuirks, table, col string) string
}

var quirks = map[string]*dialectQuirks{
	"mysql": {
		quoteOpen: "`", quoteClose: "`",
		supportsAlterColumnType: true, supportsDropColumn: true,
		supportsInlineComment: true, ifExists: true, ifNotExists: true,
		identityClause: "AUTO_INCREMENT",
		// MySQL은 MODIFY COLUMN으로 전체 정의를 다시 써야 한다.
		// 따라서 타입/NULL/기본값 변경이 하나의 문장으로 합쳐진다.
		alterColumnType: func(q *dialectQuirks, table, col, typ string, nullable bool) string {
			return fmt.Sprintf("ALTER TABLE %s MODIFY COLUMN %s %s%s", table, col, typ, nullSuffix(nullable))
		},
		setNullability: func(q *dialectQuirks, table, col, typ string, nullable bool) string {
			return fmt.Sprintf("ALTER TABLE %s MODIFY COLUMN %s %s%s", table, col, typ, nullSuffix(nullable))
		},
		setDefault: func(q *dialectQuirks, table, col, def string) string {
			return fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s SET DEFAULT %s", table, col, def)
		},
		dropDefault: func(q *dialectQuirks, table, col string) string {
			return fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s DROP DEFAULT", table, col)
		},
	},
	"postgres": {
		quoteOpen: `"`, quoteClose: `"`,
		supportsAlterColumnType: true, supportsDropColumn: true,
		commentStatement: true, ifExists: true, ifNotExists: true,
		identityClause: "GENERATED BY DEFAULT AS IDENTITY",
		alterColumnType: func(q *dialectQuirks, table, col, typ string, nullable bool) string {
			// USING 절 없이 변경 가능한 조합이 제한적이므로 명시적 캐스트를 넣어준다.
			return fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s TYPE %s USING %s::%s", table, col, typ, col, typ)
		},
		setNullability: func(q *dialectQuirks, table, col, typ string, nullable bool) string {
			if nullable {
				return fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s DROP NOT NULL", table, col)
			}
			return fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s SET NOT NULL", table, col)
		},
		setDefault: func(q *dialectQuirks, table, col, def string) string {
			return fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s SET DEFAULT %s", table, col, def)
		},
		dropDefault: func(q *dialectQuirks, table, col string) string {
			return fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s DROP DEFAULT", table, col)
		},
	},
	"mssql": {
		quoteOpen: "[", quoteClose: "]",
		supportsAlterColumnType: true, supportsDropColumn: true,
		ifExists: true, ifNotExists: false,
		identityClause: "IDENTITY(1,1)",
		alterColumnType: func(q *dialectQuirks, table, col, typ string, nullable bool) string {
			return fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s %s%s", table, col, typ, nullSuffix(nullable))
		},
		setNullability: func(q *dialectQuirks, table, col, typ string, nullable bool) string {
			return fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s %s%s", table, col, typ, nullSuffix(nullable))
		},
		// MS-SQL의 기본값은 이름 있는 제약이라 ADD/DROP CONSTRAINT로 다뤄야 한다.
		setDefault: func(q *dialectQuirks, table, col, def string) string {
			return fmt.Sprintf("ALTER TABLE %s ADD DEFAULT %s FOR %s", table, def, col)
		},
		dropDefault: nil, // 제약 이름을 알아야 하므로 렌더러에서 경고를 남긴다
	},
	"oracle": {
		quoteOpen: `"`, quoteClose: `"`,
		supportsAlterColumnType: true, supportsDropColumn: true,
		commentStatement: true, ifExists: false, ifNotExists: false,
		identityClause: "GENERATED BY DEFAULT AS IDENTITY",
		alterColumnType: func(q *dialectQuirks, table, col, typ string, nullable bool) string {
			return fmt.Sprintf("ALTER TABLE %s MODIFY (%s %s)", table, col, typ)
		},
		setNullability: func(q *dialectQuirks, table, col, typ string, nullable bool) string {
			if nullable {
				return fmt.Sprintf("ALTER TABLE %s MODIFY (%s NULL)", table, col)
			}
			return fmt.Sprintf("ALTER TABLE %s MODIFY (%s NOT NULL)", table, col)
		},
		setDefault: func(q *dialectQuirks, table, col, def string) string {
			return fmt.Sprintf("ALTER TABLE %s MODIFY (%s DEFAULT %s)", table, col, def)
		},
		dropDefault: func(q *dialectQuirks, table, col string) string {
			return fmt.Sprintf("ALTER TABLE %s MODIFY (%s DEFAULT NULL)", table, col)
		},
	},
	"sqlite": {
		quoteOpen: `"`, quoteClose: `"`,
		// SQLite의 ALTER TABLE은 컬럼 추가/이름변경/삭제만 지원한다.
		// 타입·제약 변경은 테이블 재작성이 필요하므로 계획에 경고를 남긴다.
		supportsAlterColumnType: false, supportsDropColumn: true,
		ifExists: true, ifNotExists: true,
		identityClause: "AUTOINCREMENT",
	},
}

func nullSuffix(nullable bool) string {
	if nullable {
		return " NULL"
	}
	return " NOT NULL"
}

// BuildPlan은 diff 결과를 대상 dialect의 실행 계획으로 변환한다.
//
// 문장 순서는 의존성을 고려해 정렬한다: 제약 해제 → 구조 변경 → 제약 재설정.
// 그렇지 않으면 FK가 걸린 컬럼을 바꿀 때 실패한다.
func BuildPlan(dialect string, diff *DiffResult) *Plan {
	q, ok := quirks[dialect]
	if !ok {
		return &Plan{Dialect: dialect, Warnings: []string{
			fmt.Sprintf("%s dialect는 DDL 생성을 지원하지 않습니다", dialect),
		}}
	}
	p := &Plan{Dialect: dialect}
	r := &renderer{q: q, dialect: dialect, plan: p}

	for _, c := range order(diff.Changes) {
		r.render(c)
	}
	for _, u := range diff.Unsupported {
		p.Warnings = append(p.Warnings, u)
	}
	// down은 up의 역순으로 실행되어야 한다.
	reverse(p.Down)
	return p
}

// order는 변경을 실행 가능한 순서로 재배열한다.
func order(changes []Change) []Change {
	// 낮은 값이 먼저 실행된다.
	phase := map[ChangeKind]int{
		DropForeign: 0, DropCheck: 0, DropIndex: 1, DropPrimary: 2,
		DropView:   3,
		CreateEnum: 4, AlterEnum: 4,
		CreateTable: 5,
		AddColumn:   6,
		AlterColumn: 7, AlterTable: 7,
		DropColumn: 8,
		AddPrimary: 9, AddIndex: 10, AddCheck: 11, AddForeign: 12,
		CreateView: 13, ReplaceView: 13,
		DropTable: 14,
		DropEnum:  15,
	}
	out := make([]Change, len(changes))
	copy(out, changes)
	// 안정 정렬이므로 같은 단계 안에서는 diff가 만든 순서가 유지된다.
	sort.SliceStable(out, func(i, j int) bool { return phase[out[i].Kind] < phase[out[j].Kind] })
	return out
}

type renderer struct {
	q       *dialectQuirks
	dialect string
	plan    *Plan
	// createdTables는 이 계획에서 새로 만든 테이블이다.
	// SQLite처럼 ALTER로 제약을 추가할 수 없는 dialect에서 제약을 CREATE TABLE에
	// 인라인했는지 판단하는 데 쓴다.
	createdTables map[string]bool
}

func (r *renderer) markCreated(t *Table) {
	if r.createdTables == nil {
		r.createdTables = map[string]bool{}
	}
	r.createdTables[t.Key()] = true
}

func (r *renderer) wasCreated(t *Table) bool {
	return t != nil && r.createdTables[t.Key()]
}

// inlinesConstraints는 이 dialect가 제약을 CREATE TABLE에만 넣을 수 있는지 여부다.
func (r *renderer) inlinesConstraints() bool { return r.dialect == "sqlite" }

func (r *renderer) up(c Change, sql, note string) {
	r.plan.Up = append(r.plan.Up, Statement{
		SQL: sql, Kind: c.Kind, Table: c.Table, Object: c.Object,
		Destructive: c.Destructive, Note: note,
	})
}

func (r *renderer) down(c Change, sql, note string) {
	r.plan.Down = append(r.plan.Down, Statement{
		SQL: sql, Kind: c.Kind, Table: c.Table, Object: c.Object, Note: note,
	})
}

// irreversible은 down을 만들 수 없는 변경을 기록한다.
// 롤백 불가를 조용히 넘기지 않고 계획에 명시해야 승인자가 판단할 수 있다.
func (r *renderer) irreversible(c Change, reason string) {
	r.plan.Irreversible = append(r.plan.Irreversible,
		fmt.Sprintf("%s: %s", c.Summary, reason))
}

func (r *renderer) warn(format string, args ...any) {
	msg := fmt.Sprintf(format, args...)
	for _, w := range r.plan.Warnings {
		if w == msg {
			return
		}
	}
	r.plan.Warnings = append(r.plan.Warnings, msg)
}

func (r *renderer) render(c Change) {
	switch c.Kind {
	case CreateTable:
		r.createTable(c)
	case DropTable:
		r.dropTable(c)
	case AddColumn:
		r.addColumn(c)
	case DropColumn:
		r.dropColumn(c)
	case AlterColumn:
		r.alterColumn(c)
	case AlterTable:
		r.tableComment(c)
	case AddPrimary:
		r.addPrimary(c)
	case DropPrimary:
		r.dropPrimary(c)
	case AddIndex:
		r.addIndex(c)
	case DropIndex:
		r.dropIndex(c)
	case AddForeign:
		r.addForeign(c)
	case DropForeign:
		r.dropForeign(c)
	case AddCheck:
		r.addCheck(c)
	case DropCheck:
		r.dropCheck(c)
	case CreateEnum:
		r.createEnum(c)
	case DropEnum:
		r.dropEnum(c)
	case AlterEnum:
		r.alterEnum(c)
	case CreateView, ReplaceView:
		r.createView(c)
	case DropView:
		r.dropView(c)
	}
}

// ---------- 식별자/리터럴 ----------

func (r *renderer) id(name string) string {
	// 식별자에 인용부호가 들어오면 dialect 규칙대로 이스케이프한다.
	escaped := strings.ReplaceAll(name, r.q.quoteClose, r.q.quoteClose+r.q.quoteClose)
	return r.q.quoteOpen + escaped + r.q.quoteClose
}

func (r *renderer) tableName(t *Table) string {
	if t == nil {
		return ""
	}
	if t.Namespace == "" {
		return r.id(t.Name)
	}
	return r.id(t.Namespace) + "." + r.id(t.Name)
}

func (r *renderer) tableNameParts(namespace, name string) string {
	if namespace == "" {
		return r.id(name)
	}
	return r.id(namespace) + "." + r.id(name)
}

func quoteLiteral(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

// ---------- 테이블 ----------

func (r *renderer) createTable(c Change) {
	t := c.TableRef
	if t == nil {
		return
	}
	var b strings.Builder
	ine := ""
	if r.q.ifNotExists {
		ine = "IF NOT EXISTS "
	}
	fmt.Fprintf(&b, "CREATE TABLE %s%s (\n", ine, r.tableName(t))

	parts := []string{}
	for _, col := range t.Columns {
		parts = append(parts, "  "+r.columnDef(t, col))
	}
	// SQLite에서 rowid 별칭(INTEGER PRIMARY KEY AUTOINCREMENT)은 컬럼 정의에
	// 인라인되므로 테이블 레벨 PRIMARY KEY 절을 중복해서 넣으면 문법 오류가 된다.
	if t.PrimaryKey != nil && len(t.PrimaryKey.Columns) > 0 && sqliteInlinePKColumn(r.dialect, t) == nil {
		parts = append(parts, "  "+r.primaryKeyClause(t.PrimaryKey))
	}
	for _, ck := range t.Checks {
		parts = append(parts, fmt.Sprintf("  CONSTRAINT %s CHECK (%s)", r.id(ck.Name), ck.Expression))
	}
	// SQLite는 ALTER TABLE로 외래키를 추가할 수 없으므로 여기서 인라인해야 한다.
	if r.inlinesConstraints() {
		for _, fk := range t.ForeignKeys {
			parts = append(parts, "  "+r.foreignKeyClause(t, fk))
		}
	}
	b.WriteString(strings.Join(parts, ",\n"))
	b.WriteString("\n)")
	r.markCreated(t)

	if r.dialect == "mysql" {
		if engine := t.Options["engine"]; engine != "" {
			fmt.Fprintf(&b, " ENGINE=%s", engine)
		}
		if charset := t.Options["charset"]; charset != "" {
			fmt.Fprintf(&b, " DEFAULT CHARSET=%s", charset)
		}
		if t.Comment != "" {
			fmt.Fprintf(&b, " COMMENT=%s", quoteLiteral(t.Comment))
		}
	}
	r.up(c, b.String(), "")

	// 주석을 별도 문장으로 내는 dialect
	if r.q.commentStatement {
		if t.Comment != "" {
			r.up(c, fmt.Sprintf("COMMENT ON TABLE %s IS %s", r.tableName(t), quoteLiteral(t.Comment)), "")
		}
		for _, col := range t.Columns {
			if col.Comment != "" {
				r.up(c, fmt.Sprintf("COMMENT ON COLUMN %s.%s IS %s",
					r.tableName(t), r.id(col.Name), quoteLiteral(col.Comment)), "")
			}
		}
	}
	if r.dialect == "mssql" {
		if t.Comment != "" {
			r.up(c, mssqlSetDescription(t, "", t.Comment), "")
		}
		for _, col := range t.Columns {
			if col.Comment != "" {
				r.up(c, mssqlSetDescription(t, col.Name, col.Comment), "")
			}
		}
	}

	// 인덱스는 테이블 생성 후 별도로 만든다 (dialect별 문법 통일).
	for _, idx := range t.Indexes {
		r.up(c, r.createIndexSQL(t, idx), "")
	}

	r.down(c, fmt.Sprintf("DROP TABLE %s%s", r.ifExistsClause(), r.tableName(t)), "")
}

func (r *renderer) dropTable(c Change) {
	t := c.OldTable
	if t == nil {
		return
	}
	r.up(c, fmt.Sprintf("DROP TABLE %s%s", r.ifExistsClause(), r.tableName(t)), "")

	// 롤백은 테이블 구조를 되살릴 수 있지만 데이터는 되살릴 수 없다.
	restore := Change{Kind: CreateTable, Table: c.Table, TableRef: t}
	saved := r.plan.Up
	r.plan.Up = nil
	r.createTable(restore) // Up에 생성문을 만들고
	generated := r.plan.Up
	r.plan.Up = saved
	for _, s := range generated { // 그것을 Down으로 옮긴다
		r.down(c, s.SQL, "")
	}
	r.irreversible(c, "구조는 복원되지만 데이터는 복원되지 않습니다")
}

func (r *renderer) ifExistsClause() string {
	if r.q.ifExists {
		return "IF EXISTS "
	}
	return ""
}

// columnDef는 컬럼 정의 절을 만든다.
// t는 SQLite의 rowid 별칭 판정에 필요하며, ALTER 문맥에서도 소속 테이블을 넘긴다.
func (r *renderer) columnDef(t *Table, col *Column) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s %s", r.id(col.Name), RenderType(r.dialect, col.Type, col.RawType))

	if col.Generated != "" {
		fmt.Fprintf(&b, " GENERATED ALWAYS AS (%s)", col.Generated)
		return b.String()
	}

	if col.Identity {
		// SQLite의 AUTOINCREMENT는 독립적인 컬럼 제약이 아니다.
		// "INTEGER PRIMARY KEY AUTOINCREMENT" 조합에서만 유효하며,
		// 이때 NOT NULL과 DEFAULT는 쓸 수 없다(rowid 별칭이므로 불필요).
		if r.dialect == "sqlite" {
			if pkCol := sqliteInlinePKColumn(r.dialect, t); pkCol != nil && pkCol == col {
				b.WriteString(" PRIMARY KEY AUTOINCREMENT")
				return b.String()
			}
			r.warn("SQLite에서 %s 컬럼의 자동증가는 단일 INTEGER 기본키에만 적용할 수 있어 생략했습니다",
				col.Name)
		} else {
			fmt.Fprintf(&b, " %s", r.q.identityClause)
		}
	}
	if !col.Nullable {
		b.WriteString(" NOT NULL")
	}
	if col.HasDefault && col.Default != "" && !col.Identity {
		fmt.Fprintf(&b, " DEFAULT %s", col.Default)
	}
	if col.Comment != "" && r.q.supportsInlineComment {
		fmt.Fprintf(&b, " COMMENT %s", quoteLiteral(col.Comment))
	}
	return b.String()
}

// sqliteInlinePKColumn은 SQLite에서 "INTEGER PRIMARY KEY AUTOINCREMENT"로
// 인라인해야 하는 컬럼을 반환한다. 해당 없으면 nil이다.
//
// 조건: dialect가 sqlite이고, 기본키가 단일 컬럼이며, 그 컬럼이 자동증가 정수여야 한다.
// 이 조합만이 SQLite의 rowid 별칭이 되어 AUTOINCREMENT를 쓸 수 있다.
func sqliteInlinePKColumn(dialect string, t *Table) *Column {
	if dialect != "sqlite" || t == nil || t.PrimaryKey == nil || len(t.PrimaryKey.Columns) != 1 {
		return nil
	}
	col := t.Column(t.PrimaryKey.Columns[0])
	if col == nil || !col.Identity {
		return nil
	}
	switch col.Type.Base {
	case TypeSmallInt, TypeInt, TypeBigInt:
		return col
	}
	return nil
}

func (r *renderer) primaryKeyClause(pk *PrimaryKey) string {
	cols := make([]string, len(pk.Columns))
	for i, c := range pk.Columns {
		cols[i] = r.id(c)
	}
	if pk.Name != "" {
		return fmt.Sprintf("CONSTRAINT %s PRIMARY KEY (%s)", r.id(pk.Name), strings.Join(cols, ", "))
	}
	return fmt.Sprintf("PRIMARY KEY (%s)", strings.Join(cols, ", "))
}

func (r *renderer) tableComment(c Change) {
	t := c.TableRef
	if t == nil {
		return
	}
	newComment := c.Attrs["comment"]
	oldComment := c.Attrs["oldComment"]
	switch r.dialect {
	case "mysql":
		r.up(c, fmt.Sprintf("ALTER TABLE %s COMMENT=%s", r.tableName(t), quoteLiteral(newComment)), "")
		r.down(c, fmt.Sprintf("ALTER TABLE %s COMMENT=%s", r.tableName(t), quoteLiteral(oldComment)), "")
	case "postgres", "oracle":
		r.up(c, fmt.Sprintf("COMMENT ON TABLE %s IS %s", r.tableName(t), quoteLiteral(newComment)), "")
		r.down(c, fmt.Sprintf("COMMENT ON TABLE %s IS %s", r.tableName(t), quoteLiteral(oldComment)), "")
	case "mssql":
		r.up(c, mssqlSetDescription(t, "", newComment), "")
		r.down(c, mssqlSetDescription(t, "", oldComment), "")
	default:
		r.warn("%s는 테이블 주석 변경을 DDL로 지원하지 않습니다 (%s)", r.dialect, t.Display())
	}
}

// mssqlSetDescription은 MS-SQL의 주석(확장 속성) 설정 문장을 만든다.
//
// MS-SQL에는 COMMENT ON이 없고 sp_addextendedproperty만 있는데, 이미 값이 있으면
// 실패한다. 마이그레이션은 재실행 가능해야 하므로 존재 여부에 따라 add/update를
// 분기하는 블록을 생성한다. columnName이 비어 있으면 테이블 주석이다.
func mssqlSetDescription(t *Table, columnName, comment string) string {
	ns := t.Namespace
	if ns == "" {
		ns = "dbo"
	}
	objectID := fmt.Sprintf("OBJECT_ID(N'[%s].[%s]')", ns, t.Name)

	levels := fmt.Sprintf(
		"@level0type = N'SCHEMA', @level0name = N%s, @level1type = N'TABLE', @level1name = N%s",
		quoteLiteral(ns), quoteLiteral(t.Name))
	minor := "0"
	if columnName != "" {
		levels += fmt.Sprintf(", @level2type = N'COLUMN', @level2name = N%s", quoteLiteral(columnName))
		minor = fmt.Sprintf("COLUMNPROPERTY(%s, N%s, 'ColumnId')", objectID, quoteLiteral(columnName))
	}

	args := fmt.Sprintf("@name = N'MS_Description', @value = N%s, %s", quoteLiteral(comment), levels)
	return fmt.Sprintf(`IF EXISTS (SELECT 1 FROM sys.extended_properties
	WHERE major_id = %s AND minor_id = %s AND name = 'MS_Description')
	EXEC sys.sp_updateextendedproperty %s;
ELSE
	EXEC sys.sp_addextendedproperty %s`, objectID, minor, args, args)
}

// ---------- 컬럼 ----------

func (r *renderer) addColumn(c Change) {
	t, col := c.TableRef, c.Column
	if t == nil || col == nil {
		return
	}
	r.up(c, fmt.Sprintf("ALTER TABLE %s ADD COLUMN %s", r.tableName(t), r.columnDef(t, col)),
		noteIf(c.Destructive, c.LossyDetail))

	if col.Comment != "" {
		switch {
		case r.q.commentStatement:
			r.up(c, fmt.Sprintf("COMMENT ON COLUMN %s.%s IS %s",
				r.tableName(t), r.id(col.Name), quoteLiteral(col.Comment)), "")
		case r.dialect == "mssql":
			r.up(c, mssqlSetDescription(t, col.Name, col.Comment), "")
		}
	}
	r.down(c, fmt.Sprintf("ALTER TABLE %s DROP COLUMN %s", r.tableName(t), r.id(col.Name)), "")
}

func (r *renderer) dropColumn(c Change) {
	t, col := c.TableRef, c.OldColumn
	if t == nil || col == nil {
		return
	}
	if !r.q.supportsDropColumn {
		r.warn("%s는 컬럼 삭제를 지원하지 않습니다. 테이블 재작성이 필요합니다 (%s.%s)",
			r.dialect, t.Display(), col.Name)
		return
	}
	r.up(c, fmt.Sprintf("ALTER TABLE %s DROP COLUMN %s", r.tableName(t), r.id(col.Name)),
		"이 컬럼의 데이터가 삭제됩니다")
	// 구조는 되살리되 값은 되살릴 수 없다.
	r.down(c, fmt.Sprintf("ALTER TABLE %s ADD COLUMN %s", r.tableName(t), r.columnDef(t, col)), "")
	r.irreversible(c, "컬럼 구조는 복원되지만 값은 복원되지 않습니다")
}

func (r *renderer) alterColumn(c Change) {
	t, col, old := c.TableRef, c.Column, c.OldColumn
	if t == nil || col == nil || old == nil {
		return
	}
	table := r.tableName(t)
	colID := r.id(col.Name)

	if !r.q.supportsAlterColumnType {
		// SQLite: 컬럼 정의 변경은 테이블 재작성(임시 테이블 생성 → 복사 → 교체)이 필요하다.
		// 자동 생성하면 인덱스/트리거/FK 복원까지 책임져야 해 위험하므로 명시적으로 막는다.
		_, typeChanged := c.Attrs["type"]
		_, nullChanged := c.Attrs["nullable"]
		_, defChanged := c.Attrs["default"]
		if typeChanged || nullChanged || defChanged {
			r.warn("SQLite는 컬럼 정의 변경(ALTER COLUMN)을 지원하지 않습니다. "+
				"%s.%s 은 테이블 재작성이 필요하며 자동 생성 대상에서 제외했습니다", t.Display(), col.Name)
			r.irreversible(c, "SQLite 제약으로 DDL을 생성하지 못했습니다")
			return
		}
	}

	newType := RenderType(r.dialect, col.Type, col.RawType)
	oldType := RenderType(r.dialect, old.Type, old.RawType)
	_, typeChanged := c.Attrs["type"]
	_, nullChanged := c.Attrs["nullable"]

	if r.dialect == "mysql" {
		// MySQL의 MODIFY COLUMN은 정의 전체를 다시 쓴다. 따라서 타입·NULL·기본값·주석
		// 변경이 어떤 조합으로 오더라도 한 문장으로 처리되며, 개별 처리보다 정확하다.
		r.up(c, fmt.Sprintf("ALTER TABLE %s MODIFY COLUMN %s", table, r.columnDef(t, col)),
			noteIf(c.Destructive, c.LossyDetail))
		r.down(c, fmt.Sprintf("ALTER TABLE %s MODIFY COLUMN %s", table, r.columnDef(t, old)), "")
		return
	}

	{
		if typeChanged {
			r.up(c, r.q.alterColumnType(r.q, table, colID, newType, col.Nullable),
				noteIf(c.Destructive, c.LossyDetail))
			r.down(c, r.q.alterColumnType(r.q, table, colID, oldType, old.Nullable), "")
		}
		if nullChanged {
			r.up(c, r.q.setNullability(r.q, table, colID, newType, col.Nullable),
				noteIf(!col.Nullable, "기존 NULL 값이 있으면 실패합니다"))
			r.down(c, r.q.setNullability(r.q, table, colID, oldType, old.Nullable), "")
		}
	}

	// 기본값 변경
	if _, ok := c.Attrs["default"]; ok {
		r.renderDefaultChange(c, table, colID, col, old)
	}

	// 주석 변경
	if _, ok := c.Attrs["comment"]; ok {
		switch {
		case r.q.commentStatement:
			r.up(c, fmt.Sprintf("COMMENT ON COLUMN %s.%s IS %s", table, colID, quoteLiteral(col.Comment)), "")
			r.down(c, fmt.Sprintf("COMMENT ON COLUMN %s.%s IS %s", table, colID, quoteLiteral(old.Comment)), "")
		case r.dialect == "mssql":
			r.up(c, mssqlSetDescription(t, col.Name, col.Comment), "")
			r.down(c, mssqlSetDescription(t, col.Name, old.Comment), "")
		}
	}
}

func (r *renderer) renderDefaultChange(c Change, table, colID string, col, old *Column) {
	if col.HasDefault && col.Default != "" {
		r.up(c, r.q.setDefault(r.q, table, colID, col.Default), "")
	} else if r.q.dropDefault != nil {
		r.up(c, r.q.dropDefault(r.q, table, colID), "")
	} else {
		r.warn("%s에서 기본값 제거는 제약 이름이 필요해 자동 생성하지 못했습니다 (%s.%s)",
			r.dialect, c.Table, col.Name)
	}

	if old.HasDefault && old.Default != "" {
		r.down(c, r.q.setDefault(r.q, table, colID, old.Default), "")
	} else if r.q.dropDefault != nil {
		r.down(c, r.q.dropDefault(r.q, table, colID), "")
	}
}

// ---------- 제약 / 인덱스 ----------

func (r *renderer) addPrimary(c Change) {
	t, pk := c.TableRef, c.PrimaryKey
	if t == nil || pk == nil {
		return
	}
	r.up(c, fmt.Sprintf("ALTER TABLE %s ADD %s", r.tableName(t), r.primaryKeyClause(pk)), "")
	r.down(c, r.dropPrimarySQL(t, pk), "")
}

func (r *renderer) dropPrimary(c Change) {
	t, pk := c.TableRef, c.OldPrimary
	if t == nil || pk == nil {
		return
	}
	r.up(c, r.dropPrimarySQL(t, pk), "")
	r.down(c, fmt.Sprintf("ALTER TABLE %s ADD %s", r.tableName(t), r.primaryKeyClause(pk)), "")
}

func (r *renderer) dropPrimarySQL(t *Table, pk *PrimaryKey) string {
	if r.dialect == "mysql" {
		return fmt.Sprintf("ALTER TABLE %s DROP PRIMARY KEY", r.tableName(t))
	}
	name := pk.Name
	if name == "" {
		// 이름이 없으면 DB가 자동 생성한 이름을 알 수 없다.
		r.warn("%s의 기본키 제약 이름을 알 수 없어 DROP 문에 플레이스홀더를 넣었습니다. 실행 전 확인하세요", t.Display())
		name = "<PK_CONSTRAINT_NAME>"
	}
	return fmt.Sprintf("ALTER TABLE %s DROP CONSTRAINT %s", r.tableName(t), r.id(name))
}

func (r *renderer) createIndexSQL(t *Table, idx *Index) string {
	unique := ""
	if idx.Unique {
		unique = "UNIQUE "
	}
	cols := make([]string, 0, len(idx.Columns))
	for _, p := range idx.Columns {
		expr := r.id(p.Column)
		if p.Expression != "" {
			expr = "(" + p.Expression + ")"
		}
		if p.Descending {
			expr += " DESC"
		}
		cols = append(cols, expr)
	}
	ine := ""
	if r.q.ifNotExists && r.dialect != "mysql" {
		// MySQL은 CREATE INDEX IF NOT EXISTS를 지원하지 않는다.
		ine = "IF NOT EXISTS "
	}
	sql := fmt.Sprintf("CREATE %sINDEX %s%s ON %s (%s)",
		unique, ine, r.id(idx.Name), r.tableName(t), strings.Join(cols, ", "))
	if idx.Where != "" && (r.dialect == "postgres" || r.dialect == "mssql" || r.dialect == "sqlite") {
		sql += " WHERE " + idx.Where
	}
	return sql
}

func (r *renderer) dropIndexSQL(t *Table, idx *Index) string {
	switch r.dialect {
	case "mysql":
		return fmt.Sprintf("DROP INDEX %s ON %s", r.id(idx.Name), r.tableName(t))
	case "mssql":
		return fmt.Sprintf("DROP INDEX %s ON %s", r.id(idx.Name), r.tableName(t))
	case "oracle":
		return fmt.Sprintf("DROP INDEX %s", r.id(idx.Name))
	default:
		return fmt.Sprintf("DROP INDEX %s%s", r.ifExistsClause(), r.id(idx.Name))
	}
}

func (r *renderer) addIndex(c Change) {
	t, idx := c.TableRef, c.Index
	if t == nil || idx == nil {
		return
	}
	r.up(c, r.createIndexSQL(t, idx), "")
	r.down(c, r.dropIndexSQL(t, idx), "")
}

func (r *renderer) dropIndex(c Change) {
	t, idx := c.TableRef, c.OldIndex
	if t == nil || idx == nil {
		return
	}
	r.up(c, r.dropIndexSQL(t, idx), "")
	r.down(c, r.createIndexSQL(t, idx), "")
}

// foreignKeyClause는 외래키 제약 절을 만든다.
// owner는 제약이 붙는 테이블이며, 참조 대상의 네임스페이스를 보완하는 데 쓴다.
func (r *renderer) foreignKeyClause(owner *Table, fk *ForeignKey) string {
	cols := make([]string, len(fk.Columns))
	for i, c := range fk.Columns {
		cols[i] = r.id(c)
	}
	refCols := make([]string, len(fk.RefColumns))
	for i, c := range fk.RefColumns {
		refCols[i] = r.id(c)
	}

	// IR은 참조 대상이 같은 네임스페이스일 때 RefNamespace를 비워 이식성을 확보한다.
	// 그러나 생성되는 DDL에서 네임스페이스를 생략하면 세션의 기본 스키마로 해석되어,
	// 대상 스키마가 기본값과 다를 때 엉뚱한 테이블을 참조하게 된다.
	// 따라서 소유 테이블의 네임스페이스로 명시적으로 보완한다.
	refNS := fk.RefNamespace
	if refNS == "" && owner != nil {
		refNS = owner.Namespace
	}

	sql := fmt.Sprintf("CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (%s)",
		r.id(fk.Name), strings.Join(cols, ", "),
		r.tableNameParts(refNS, fk.RefTable), strings.Join(refCols, ", "))
	if a := normalizeAction(fk.OnDelete); a != "NO ACTION" {
		sql += " ON DELETE " + a
	}
	if a := normalizeAction(fk.OnUpdate); a != "NO ACTION" && r.dialect != "oracle" {
		// Oracle은 ON UPDATE를 지원하지 않는다.
		sql += " ON UPDATE " + a
	}
	return sql
}

func (r *renderer) addForeign(c Change) {
	t, fk := c.TableRef, c.ForeignKey
	if t == nil || fk == nil {
		return
	}
	if r.inlinesConstraints() {
		// 이 계획에서 테이블을 새로 만들었다면 FK는 CREATE TABLE에 이미 인라인되어 있다.
		if r.wasCreated(t) {
			return
		}
		r.warn("SQLite는 기존 테이블에 외래키를 추가할 수 없습니다. 테이블 재작성이 필요합니다 (%s.%s)",
			t.Display(), fk.Name)
		r.irreversible(c, "SQLite 제약으로 DDL을 생성하지 못했습니다")
		return
	}
	r.up(c, fmt.Sprintf("ALTER TABLE %s ADD %s", r.tableName(t), r.foreignKeyClause(t, fk)),
		"참조 무결성을 위반하는 기존 데이터가 있으면 실패합니다")
	r.down(c, r.dropConstraintSQL(t, fk.Name), "")
}

func (r *renderer) dropForeign(c Change) {
	t, fk := c.TableRef, c.OldFK
	if t == nil || fk == nil {
		return
	}
	if r.dialect == "sqlite" {
		r.warn("SQLite는 외래키 삭제를 지원하지 않습니다 (%s.%s)", t.Display(), fk.Name)
		return
	}
	r.up(c, r.dropConstraintSQL(t, fk.Name), "")
	r.down(c, fmt.Sprintf("ALTER TABLE %s ADD %s", r.tableName(t), r.foreignKeyClause(t, fk)), "")
}

func (r *renderer) dropConstraintSQL(t *Table, name string) string {
	if r.dialect == "mysql" {
		return fmt.Sprintf("ALTER TABLE %s DROP FOREIGN KEY %s", r.tableName(t), r.id(name))
	}
	return fmt.Sprintf("ALTER TABLE %s DROP CONSTRAINT %s", r.tableName(t), r.id(name))
}

func (r *renderer) addCheck(c Change) {
	t, ck := c.TableRef, c.CheckRef
	if t == nil || ck == nil {
		return
	}
	if r.inlinesConstraints() {
		// CREATE TABLE에 이미 인라인되어 있다.
		if r.wasCreated(t) {
			return
		}
		r.warn("SQLite는 기존 테이블에 체크 제약을 추가할 수 없습니다 (%s.%s)", t.Display(), ck.Name)
		r.irreversible(c, "SQLite 제약으로 DDL을 생성하지 못했습니다")
		return
	}
	r.up(c, fmt.Sprintf("ALTER TABLE %s ADD CONSTRAINT %s CHECK (%s)",
		r.tableName(t), r.id(ck.Name), ck.Expression), c.LossyDetail)
	r.down(c, fmt.Sprintf("ALTER TABLE %s DROP CONSTRAINT %s", r.tableName(t), r.id(ck.Name)), "")
}

func (r *renderer) dropCheck(c Change) {
	t, ck := c.TableRef, c.OldCheck
	if t == nil || ck == nil {
		return
	}
	if r.dialect == "sqlite" {
		r.warn("SQLite는 체크 제약 삭제를 지원하지 않습니다 (%s.%s)", t.Display(), ck.Name)
		return
	}
	r.up(c, fmt.Sprintf("ALTER TABLE %s DROP %s %s", r.tableName(t), checkKeyword(r.dialect), r.id(ck.Name)), "")
	r.down(c, fmt.Sprintf("ALTER TABLE %s ADD CONSTRAINT %s CHECK (%s)",
		r.tableName(t), r.id(ck.Name), ck.Expression), "")
}

func checkKeyword(dialect string) string {
	if dialect == "mysql" {
		return "CHECK"
	}
	return "CONSTRAINT"
}

// ---------- enum / 뷰 ----------

func (r *renderer) createEnum(c Change) {
	e := c.EnumRef
	if e == nil {
		return
	}
	if r.dialect != "postgres" {
		// 다른 dialect에서는 enum이 컬럼 정의에 인라인으로 들어가거나 VARCHAR로 렌더된다.
		return
	}
	r.up(c, fmt.Sprintf("CREATE TYPE %s AS ENUM (%s)",
		r.tableNameParts(e.Namespace, e.Name), quoteList(e.Values, "'")), "")
	r.down(c, fmt.Sprintf("DROP TYPE %s%s", r.ifExistsClause(), r.tableNameParts(e.Namespace, e.Name)), "")
}

func (r *renderer) dropEnum(c Change) {
	e := c.OldEnum
	if e == nil || r.dialect != "postgres" {
		return
	}
	r.up(c, fmt.Sprintf("DROP TYPE %s%s", r.ifExistsClause(), r.tableNameParts(e.Namespace, e.Name)), "")
	r.down(c, fmt.Sprintf("CREATE TYPE %s AS ENUM (%s)",
		r.tableNameParts(e.Namespace, e.Name), quoteList(e.Values, "'")), "")
}

func (r *renderer) alterEnum(c Change) {
	e, old := c.EnumRef, c.OldEnum
	if e == nil || old == nil || r.dialect != "postgres" {
		return
	}
	added := missing(e.Values, old.Values)
	removed := missing(old.Values, e.Values)
	name := r.tableNameParts(e.Namespace, e.Name)

	for _, v := range added {
		r.up(c, fmt.Sprintf("ALTER TYPE %s ADD VALUE IF NOT EXISTS %s", name, quoteLiteral(v)), "")
	}
	if len(removed) > 0 {
		// PostgreSQL은 enum 값 제거를 지원하지 않는다. 타입 재생성이 필요하다.
		r.warn("PostgreSQL은 enum 값 제거를 지원하지 않습니다. %s 타입은 재생성이 필요합니다 (제거 대상: %s)",
			e.Name, strings.Join(removed, ", "))
		r.irreversible(c, "enum 값 제거는 타입 재생성이 필요합니다")
	}
	// 값 추가는 되돌릴 수 없다 (PostgreSQL이 제거를 지원하지 않으므로).
	if len(added) > 0 {
		r.irreversible(c, fmt.Sprintf("추가된 enum 값(%s)은 제거할 수 없습니다", strings.Join(added, ", ")))
	}
}

func (r *renderer) createView(c Change) {
	v := c.ViewRef
	if v == nil {
		return
	}
	if v.Definition == "" {
		r.warn("뷰 %s의 정의를 읽지 못해 DDL을 생성하지 못했습니다", v.Key())
		return
	}
	verb := "CREATE OR REPLACE VIEW"
	if r.dialect == "mssql" && c.Kind == ReplaceView {
		verb = "ALTER VIEW"
	} else if r.dialect == "mssql" || r.dialect == "sqlite" {
		verb = "CREATE VIEW"
	}
	r.up(c, fmt.Sprintf("%s %s AS %s", verb, r.tableNameParts(v.Namespace, v.Name), v.Definition), "")
	r.down(c, fmt.Sprintf("DROP VIEW %s%s", r.ifExistsClause(), r.tableNameParts(v.Namespace, v.Name)), "")
}

func (r *renderer) dropView(c Change) {
	v := c.ViewRef
	if v == nil {
		return
	}
	r.up(c, fmt.Sprintf("DROP VIEW %s%s", r.ifExistsClause(), r.tableNameParts(v.Namespace, v.Name)), "")
	if v.Definition != "" {
		r.down(c, fmt.Sprintf("CREATE VIEW %s AS %s", r.tableNameParts(v.Namespace, v.Name), v.Definition), "")
	} else {
		r.irreversible(c, "뷰 정의를 알 수 없어 복원 SQL을 만들 수 없습니다")
	}
}

// ---------- 유틸 ----------

func noteIf(cond bool, note string) string {
	if cond {
		return note
	}
	return ""
}

func reverse[T any](s []T) {
	for i, j := 0, len(s)-1; i < j; i, j = i+1, j-1 {
		s[i], s[j] = s[j], s[i]
	}
}
