package dbx

// 통합 테스트용 스키마. 각 dialect에서 같은 논리 구조를 만든다:
//   it_users      : 자동증가 PK, 유니크 인덱스, 체크 제약, 주석, 기본값, nullable 컬럼
//   it_orders     : it_users를 CASCADE로 참조하는 외래키
//   it_order_item : 복합 기본키
//   it_user_view  : 뷰
//
// 목적은 introspect가 이 구조를 빠짐없이, 그리고 두 번 읽어도 동일하게 읽는지 확인하는 것이다.

var mysqlSetup = []string{
	`CREATE TABLE it_users (
		id BIGINT NOT NULL AUTO_INCREMENT,
		email VARCHAR(255) NOT NULL COMMENT '로그인 이메일',
		nickname VARCHAR(64) NULL,
		login_count INT NOT NULL DEFAULT 0,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY (id),
		CONSTRAINT it_users_login_count_chk CHECK (login_count >= 0)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='통합 테스트 사용자'`,
	`CREATE UNIQUE INDEX it_users_email_uq ON it_users (email)`,
	`CREATE TABLE it_orders (
		id BIGINT NOT NULL AUTO_INCREMENT,
		user_id BIGINT NOT NULL,
		status VARCHAR(16) NOT NULL DEFAULT 'new',
		amount DECIMAL(12,2) NOT NULL,
		PRIMARY KEY (id),
		CONSTRAINT it_orders_user_fk FOREIGN KEY (user_id) REFERENCES it_users (id) ON DELETE CASCADE
	) ENGINE=InnoDB`,
	`CREATE INDEX it_orders_user_idx ON it_orders (user_id)`,
	`CREATE TABLE it_order_item (
		order_id BIGINT NOT NULL,
		line_no INT NOT NULL,
		sku VARCHAR(64) NOT NULL,
		PRIMARY KEY (order_id, line_no)
	) ENGINE=InnoDB`,
	`CREATE VIEW it_user_view AS SELECT id, email FROM it_users`,
}

var postgresSetup = []string{
	`CREATE TYPE it_status AS ENUM ('new', 'paid', 'shipped')`,
	`CREATE TABLE it_users (
		id BIGSERIAL PRIMARY KEY,
		email VARCHAR(255) NOT NULL,
		nickname VARCHAR(64),
		login_count INTEGER NOT NULL DEFAULT 0,
		created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
		CONSTRAINT it_users_login_count_chk CHECK (login_count >= 0)
	)`,
	`COMMENT ON TABLE it_users IS '통합 테스트 사용자'`,
	`COMMENT ON COLUMN it_users.email IS '로그인 이메일'`,
	`CREATE UNIQUE INDEX it_users_email_uq ON it_users (email)`,
	`CREATE TABLE it_orders (
		id BIGSERIAL PRIMARY KEY,
		user_id BIGINT NOT NULL,
		status it_status NOT NULL DEFAULT 'new',
		amount NUMERIC(12,2) NOT NULL,
		CONSTRAINT it_orders_user_fk FOREIGN KEY (user_id) REFERENCES it_users (id) ON DELETE CASCADE
	)`,
	`CREATE INDEX it_orders_user_idx ON it_orders (user_id)`,
	// 부분 인덱스: PostgreSQL 고유 기능이 introspect/diff에서 안정적인지 확인한다.
	`CREATE INDEX it_orders_paid_idx ON it_orders (user_id) WHERE status = 'paid'`,
	`CREATE TABLE it_order_item (
		order_id BIGINT NOT NULL,
		line_no INTEGER NOT NULL,
		sku VARCHAR(64) NOT NULL,
		PRIMARY KEY (order_id, line_no)
	)`,
	`CREATE VIEW it_user_view AS SELECT id, email FROM it_users`,
}

var mssqlSetup = []string{
	`CREATE TABLE it_users (
		id BIGINT IDENTITY(1,1) NOT NULL,
		email NVARCHAR(255) NOT NULL,
		nickname NVARCHAR(64) NULL,
		login_count INT NOT NULL CONSTRAINT it_users_login_count_df DEFAULT 0,
		created_at DATETIME2 NOT NULL CONSTRAINT it_users_created_df DEFAULT SYSUTCDATETIME(),
		CONSTRAINT it_users_pk PRIMARY KEY (id),
		CONSTRAINT it_users_login_count_chk CHECK (login_count >= 0)
	)`,
	`EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'통합 테스트 사용자',
		@level0type = N'SCHEMA', @level0name = N'dbo',
		@level1type = N'TABLE', @level1name = N'it_users'`,
	`EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'로그인 이메일',
		@level0type = N'SCHEMA', @level0name = N'dbo',
		@level1type = N'TABLE', @level1name = N'it_users',
		@level2type = N'COLUMN', @level2name = N'email'`,
	`CREATE UNIQUE INDEX it_users_email_uq ON it_users (email)`,
	`CREATE TABLE it_orders (
		id BIGINT IDENTITY(1,1) NOT NULL,
		user_id BIGINT NOT NULL,
		status NVARCHAR(16) NOT NULL CONSTRAINT it_orders_status_df DEFAULT 'new',
		amount DECIMAL(12,2) NOT NULL,
		CONSTRAINT it_orders_pk PRIMARY KEY (id),
		CONSTRAINT it_orders_user_fk FOREIGN KEY (user_id) REFERENCES it_users (id) ON DELETE CASCADE
	)`,
	`CREATE INDEX it_orders_user_idx ON it_orders (user_id)`,
	`CREATE TABLE it_order_item (
		order_id BIGINT NOT NULL,
		line_no INT NOT NULL,
		sku NVARCHAR(64) NOT NULL,
		CONSTRAINT it_order_item_pk PRIMARY KEY (order_id, line_no)
	)`,
	`CREATE VIEW it_user_view AS SELECT id, email FROM it_users`,
}

var oracleSetup = []string{
	`CREATE TABLE it_users (
		id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
		email VARCHAR2(255) NOT NULL,
		nickname VARCHAR2(64),
		login_count NUMBER(10) DEFAULT 0 NOT NULL,
		created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
		CONSTRAINT it_users_pk PRIMARY KEY (id),
		CONSTRAINT it_users_login_count_chk CHECK (login_count >= 0)
	)`,
	`COMMENT ON TABLE it_users IS '통합 테스트 사용자'`,
	`COMMENT ON COLUMN it_users.email IS '로그인 이메일'`,
	`CREATE UNIQUE INDEX it_users_email_uq ON it_users (email)`,
	`CREATE TABLE it_orders (
		id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
		user_id NUMBER(19) NOT NULL,
		status VARCHAR2(16) DEFAULT 'new' NOT NULL,
		amount NUMBER(12,2) NOT NULL,
		CONSTRAINT it_orders_pk PRIMARY KEY (id),
		CONSTRAINT it_orders_user_fk FOREIGN KEY (user_id) REFERENCES it_users (id) ON DELETE CASCADE
	)`,
	`CREATE INDEX it_orders_user_idx ON it_orders (user_id)`,
	`CREATE TABLE it_order_item (
		order_id NUMBER(19) NOT NULL,
		line_no NUMBER(10) NOT NULL,
		sku VARCHAR2(64) NOT NULL,
		CONSTRAINT it_order_item_pk PRIMARY KEY (order_id, line_no)
	)`,
	`CREATE VIEW it_user_view AS SELECT id, email FROM it_users`,
}

// Oracle에는 DROP ... IF EXISTS가 없으므로 개별 DROP을 실패 허용으로 실행한다.
var oracleTeardown = []string{
	`DROP VIEW it_user_view`,
	`DROP TABLE it_order_item CASCADE CONSTRAINTS`,
	`DROP TABLE it_orders CASCADE CONSTRAINTS`,
	`DROP TABLE it_users CASCADE CONSTRAINTS`,
}

var sqliteSetup = []string{
	`CREATE TABLE it_users (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		email VARCHAR(255) NOT NULL,
		nickname VARCHAR(64),
		login_count INTEGER NOT NULL DEFAULT 0,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		CONSTRAINT it_users_login_count_chk CHECK (login_count >= 0)
	)`,
	`CREATE UNIQUE INDEX it_users_email_uq ON it_users (email)`,
	`CREATE TABLE it_orders (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		user_id INTEGER NOT NULL,
		status VARCHAR(16) NOT NULL DEFAULT 'new',
		amount NUMERIC(12,2) NOT NULL,
		CONSTRAINT it_orders_user_fk FOREIGN KEY (user_id) REFERENCES it_users (id) ON DELETE CASCADE
	)`,
	`CREATE INDEX it_orders_user_idx ON it_orders (user_id)`,
	`CREATE TABLE it_order_item (
		order_id INTEGER NOT NULL,
		line_no INTEGER NOT NULL,
		sku VARCHAR(64) NOT NULL,
		PRIMARY KEY (order_id, line_no)
	)`,
	`CREATE VIEW it_user_view AS SELECT id, email FROM it_users`,
}
